global:
  scrape_interval: 5s   # How often to pull metrics

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["host.docker.internal:8000"]  # if FastAPI runs locally outside Docker
